-- auction stores all auctions. The primary key is generated by the database
-- so that CRUD API endpoints never need to supply an ID.
CREATE TABLE auction (
    id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    title          TEXT        NOT NULL,
    status         TEXT        NOT NULL DEFAULT 'pending'
                               CHECK (status IN ('pending', 'active', 'finished')),
    starting_price BIGINT      NOT NULL,
    starts_at      TIMESTAMPTZ NOT NULL,
    ends_at        TIMESTAMPTZ NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- bid stores every accepted bid. The primary key is generated by the Go
-- application layer (uuid.NewString) so that the bid ID is available
-- throughout the processing pipeline before the row is persisted.
CREATE TABLE bid (
    id         UUID        PRIMARY KEY,
    auction_id UUID        NOT NULL REFERENCES auction(id),
    user_id    TEXT        NOT NULL,
    amount     BIGINT      NOT NULL,
    placed_at  TIMESTAMPTZ NOT NULL
);

-- Index supporting the lateral subquery in ListActiveStates that finds the
-- highest bid per auction: WHERE auction_id = a.id ORDER BY amount DESC LIMIT 1.
CREATE INDEX ON bid (auction_id, amount DESC);
